import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import UIProvider from "~/providers/UIProvider"
import clsx from "clsx"
import { Toaster } from "react-hot-toast"
import ContextProvider from "../providers/ContextProvider"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={clsx(inter.className, "bg-[#1a1a1c] no-scroll")}>
                <Toaster position="bottom-left"/>
                <ContextProvider>
                    <UIProvider>{children}</UIProvider>
                </ContextProvider>
            </body>
        </html>
    )
}
